### ISSUE TITLE
Pipeline resuming execution after successful execution of Maven CI pipeline using JTE templates

### ISSUE THREAD

**Issue by Madhuri1518** [jenkinsci/templating-engine-plugin#187]
### Environment Information

- [x] Jenkins version - CloudBees CI Managed Master 2.263.1.2-rolling
- [x] Plugin version - 2.0.3
- [ ] OS

### Description

Initially build has run successfully. After sometime pipeline is resuming again and throwing an error.

We are having libraries for building application(Maven and Gradle) and for docker(build and publish). Tested the same workflow for both Maven and Gradle applications. Gradle application is working fine. But getting error for Maven application.

**Pipeline stages**

1. checkout to git rep 
2. Run application unit test cases
3. Build application
4. Docker build
5. Docker publish

**JTE configuration**
configured pipeline template in governance tier 
pipeline configuration from application git repository

**Error**
Pipeline logs at the end

```
[Pipeline] // stage
[JTE][Stage - continuous_deployment]
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
[Checks API] No suitable checks publisher found.
Finished: SUCCESS
Resuming build at Wed Feb 24 17:10:44 UTC 2021 after Jenkins restart
[Pipeline] End of Pipeline
[Checks API] No suitable checks publisher found.
java.io.FileNotFoundException: <pipeline-location>/builds/9/program.dat (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverReader.openStreamAt(RiverReader.java:188)
	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverReader.restorePickles(RiverReader.java:136)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.loadProgramAsync(CpsFlowExecution.java:784)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onLoad(CpsFlowExecution.java:750)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution(WorkflowRun.java:691)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.onLoad(WorkflowRun.java:550)
	at hudson.model.RunMap.retrieve(RunMap.java:225)
	at hudson.model.RunMap.retrieve(RunMap.java:57)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:501)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:483)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.getByNumber(AbstractLazyLoadRunMap.java:381)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.search(AbstractLazyLoadRunMap.java:346)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.newestBuild(AbstractLazyLoadRunMap.java:276)
	at jenkins.model.lazy.LazyBuildMixIn.getLastBuild(LazyBuildMixIn.java:242)
	at org.jenkinsci.plugins.workflow.job.WorkflowJob.getLastBuild(WorkflowJob.java:240)
	at org.jenkinsci.plugins.workflow.job.WorkflowJob.getLastBuild(WorkflowJob.java:103)
	at org.jenkinsci.plugins.prometheus.JobCollector.appendJobMetrics(JobCollector.java:262)
	at org.jenkinsci.plugins.prometheus.JobCollector.lambda$collect$0(JobCollector.java:220)
	at org.jenkinsci.plugins.prometheus.util.Jobs.forEachJob(Jobs.java:14)
	at org.jenkinsci.plugins.prometheus.JobCollector.collect(JobCollector.java:214)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:190)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:223)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:144)
	at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
	at org.jenkinsci.plugins.prometheus.service.DefaultPrometheusMetrics.collectMetrics(DefaultPrometheusMetrics.java:51)
	at org.jenkinsci.plugins.prometheus.service.PrometheusAsyncWorker.execute(PrometheusAsyncWorker.java:41)
	at hudson.model.AsyncPeriodicWork.lambda$doRun$0(AsyncPeriodicWork.java:100)
Caused: java.io.IOException: Failed to load build state
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$3.onSuccess(CpsFlowExecution.java:865)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$3.onSuccess(CpsFlowExecution.java:863)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$4$1.run(CpsFlowExecution.java:917)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:136)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by steven-terrana** [comment]
Thanks for reporting! Would you be able to provide steps to minimally reproduce?

**Comment by steven-terrana** [comment]
closing due to inactivity. feel free to re-open if you're able to provide a reproducible test case.

**Comment by Madhuri1518** [comment]
We are getting same error for other application(gradle) pipelines as well.
Steps to reproduce
1. Libraries are added in one git repository under folder libraries
2. Below are the pipeline configuration files added in separate git repository.
pipeline_config.groovy

```
@merge libraries{
  @override agent
  @override git
}
```

Jenkinsfile
```
node {
  continuous_integration()
  continuous_deployment()
}

```
2. Configure libraries and pipeline configuration at folder level in Jenkins
3. Configure pipeline config at Job level
```
stages{
  continuous_integration{
    checkout_scm  
    build_artifact
    build_publish_image
  }
  continuous_deployment{}
}
libraries{
  git{
    url = "ssh://git@<url>"
    credential {
      id = "credential-id"
      type = "sshKey"
    }
  }
  maven{
    args = "-X"
    image{
      registry{
          url = "<dtr-url>"
          credential = "<dtr-credential>"
          repository = "<dtr-repo>"
      }
    } 
  }
}
```

We are having multiple pipelines with different stages. So it's hard to provide all the pipeline configuration files for reproducing the error

**Comment by Madhuri1518** [comment]
@steven-terrana Please reopen the ticket or let me know if I have to create another issue for the same.

**Comment by steven-terrana** [comment]
unfortunately this is still not enough information to reproduce.  

Please provide:
1. a _**minimal**_ pipeline template
2. a _**minimal**_ pipeline configuration
3. if necessary, the **_minimal_** number of pipeline steps to reproduce

**Comment by krrishkishore** [comment]
@steven-terrana @Madhuri1518 seems to have already provided the details above not sure if those are not sufficient.

Can you please confirm if they are not.

Also, we observed that after uninstalling the prometheus plugin the issue was gone and reinstalling it re triggering the issue again.

[Pipeline] End of Pipeline
java.io.FileNotFoundException: /var/jenkins_home/<JOBPATH>/builds/28/program.dat (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverReader.openStreamAt(RiverReader.java:188)
	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverReader.restorePickles(RiverReader.java:136)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.loadProgramAsync(CpsFlowExecution.java:784)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onLoad(CpsFlowExecution.java:750)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution(WorkflowRun.java:691)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.onLoad(WorkflowRun.java:550)
	at hudson.model.RunMap.retrieve(RunMap.java:225)
	at hudson.model.RunMap.retrieve(RunMap.java:57)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:501)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:483)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.getByNumber(AbstractLazyLoadRunMap.java:381)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.search(AbstractLazyLoadRunMap.java:346)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.newestBuild(AbstractLazyLoadRunMap.java:276)
	at jenkins.model.lazy.LazyBuildMixIn.getLastBuild(LazyBuildMixIn.java:242)
	at org.jenkinsci.plugins.workflow.job.WorkflowJob.getLastBuild(WorkflowJob.java:240)
	at org.jenkinsci.plugins.workflow.job.WorkflowJob.getLastBuild(WorkflowJob.java:103)
	at org.jenkinsci.plugins.prometheus.JobCollector.appendJobMetrics(JobCollector.java:262)
	at org.jenkinsci.plugins.prometheus.JobCollector.lambda$collect$0(JobCollector.java:220)
	at org.jenkinsci.plugins.prometheus.util.Jobs.forEachJob(Jobs.java:14)
	at org.jenkinsci.plugins.prometheus.JobCollector.collect(JobCollector.java:214)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:190)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:223)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:144)
	at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
	at org.jenkinsci.plugins.prometheus.service.DefaultPrometheusMetrics.collectMetrics(DefaultPrometheusMetrics.java:51)
	at org.jenkinsci.plugins.prometheus.service.PrometheusAsyncWorker.execute(PrometheusAsyncWorker.java:41)
	at hudson.model.AsyncPeriodicWork.lambda$doRun$0(AsyncPeriodicWork.java:100)
Caused: java.io.IOException: Failed to load build state
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$3.onSuccess(CpsFlowExecution.java:865)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$3.onSuccess(CpsFlowExecution.java:863)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$4$1.run(CpsFlowExecution.java:917)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:136)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE

**Comment by krrishkishore** [comment]
Prometheus version is: 2.0.8 and Jenkins Templating Engine version: 2.0.4

**Comment by cokieffebah** [comment]
@krrishkishore to help us possibly resolve this issue, could you provide the following information:

a minimal pipeline template
a minimal pipeline configuration
if necessary, the minimal number of pipeline steps to reproduce

**Comment by krrishkishore** [comment]
@cokieffebah Madhuri already provided the required details in the ticket

**Comment by cokieffebah** [comment]
@krrishkishore Steven mentioned this bug with has some mitigations: since we have not been able to reproduce I wonder if this helps: https://issues.jenkins.io/browse/JENKINS-53775?focusedCommentId=370808&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-370808

**Comment by steven-terrana** [comment]
Can you please upgrade to the latest version of JTE and the latest version of the pipeline plugins and confirm if you're still seeing the issue? 

This seems related to: https://issues.jenkins.io/browse/JENKINS-50199

i'm unable to reproduce despite multiple attempts. 

It's likely that if this bug is present, the root cause is actually with https://github.com/jenkinsci/workflow-cps-plugin and/or https://github.com/jenkinsci/workflow-job-plugin.

**Comment by steven-terrana** [comment]
closing until steps to reproduce are identified

**Comment by AFriemann** [comment]
@steven-terrana I am seeing the same issue. Job was green and finished, then looking at it later it's failed.

We're on template engine plugin version 2.5.2

```
18:39:53  [Pipeline] End of Pipeline
18:39:55  [GitHub Checks] GitHub check (name: Jenkins, status: completed) has been published.
18:39:56  Finished: SUCCESS
19:02:53  Resuming build at Thu Sep 22 17:02:53 GMT 2022 after Jenkins restart
19:02:53  [Pipeline] End of Pipeline
19:02:53  java.io.FileNotFoundException: /var/jenkins_home/jobs/CloudOps/jobs/s3clamd/branches/PR-34/builds/44/program.dat (No such file or directory)
19:02:53  	at java.base/java.io.FileInputStream.open0(Native Method)
19:02:53  	at java.base/java.io.FileInputStream.open(Unknown Source)
19:02:53  	at java.base/java.io.FileInputStream.<init>(Unknown Source)
19:02:53  	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverReader.openStreamAt(RiverReader.java:196)
19:02:53  	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverReader.restorePickles(RiverReader.java:140)
19:02:53  	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.loadProgramAsync(CpsFlowExecution.java:774)
19:02:53  	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onLoad(CpsFlowExecution.java:740)
19:02:53  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution(WorkflowRun.java:701)
19:02:53  	at org.jenkinsci.plugins.workflow.job.WorkflowRun.onLoad(WorkflowRun.java:560)
19:02:53  	at hudson.model.RunMap.retrieve(RunMap.java:233)
19:02:53  	at hudson.model.RunMap.retrieve(RunMap.java:61)
19:02:53  	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:650)
19:02:53  	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:632)
19:02:53  	at jenkins.model.lazy.AbstractLazyLoadRunMap.getByNumber(AbstractLazyLoadRunMap.java:530)
19:02:53  	at jenkins.model.lazy.AbstractLazyLoadRunMap.search(AbstractLazyLoadRunMap.java:495)
19:02:53  	at jenkins.model.lazy.AbstractLazyLoadRunMap.newestBuild(AbstractLazyLoadRunMap.java:428)
19:02:53  	at jenkins.model.lazy.LazyBuildMixIn.getLastBuild(LazyBuildMixIn.java:244)
19:02:53  	at org.jenkinsci.plugins.workflow.job.WorkflowJob.getLastBuild(WorkflowJob.java:242)
19:02:53  	at org.jenkinsci.plugins.workflow.job.WorkflowJob.getLastBuild(WorkflowJob.java:105)
19:02:53  	at com.axis.system.jenkins.plugins.downstream.yabv.BuildFlowAction$ProjectActionFactory.createFor(BuildFlowAction.java:255)
19:02:53  	at com.axis.system.jenkins.plugins.downstream.yabv.BuildFlowAction$ProjectActionFactory.createFor(BuildFlowAction.java:245)
19:02:53  	at hudson.model.Actionable.createFor(Actionable.java:115)
19:02:53  	at hudson.model.Actionable.getActions(Actionable.java:140)
19:02:53  	at hudson.model.Job.getPermalinks(Job.java:1074)
19:02:53  	at hudson.model.Job.getDynamic(Job.java:863)
19:02:53  	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
19:02:53  	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:397)
19:02:53  	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:409)
19:02:53  	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:207)
19:02:53  	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:473)
19:02:53  	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:762)
19:02:53  	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:894)
19:02:53  	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:289)
19:02:53  	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59)
19:02:53  	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:762)
19:02:53  	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:894)
19:02:53  	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:289)
19:02:53  	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59)
19:02:53  	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:762)
19:02:53  	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:894)
19:02:53  	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:289)
19:02:53  	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59)
19:02:53  	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:762)
19:02:53  	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:894)
19:02:53  	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:690)
19:02:53  	at org.kohsuke.stapler.Stapler.service(Stapler.java:240)
19:02:53  	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
19:02:53  	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
19:02:53  	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
19:02:53  	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:157)
19:02:53  	at hudson.plugins.locale.LocaleFilter.doFilter(LocaleFilter.java:42)
19:02:53  	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
19:02:53  	at hudson.plugins.audit_trail.AuditTrailFilter.doFilter(AuditTrailFilter.java:112)
19:02:53  	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
19:02:53  	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:129)
19:02:53  	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
19:02:53  	at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:81)
19:02:53  	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
19:02:53  	at io.jenkins.plugins.extendedsecuritysettings.UnauthorizedUserHttpHeaderRestrictionFilter.doFilter(UnauthorizedUserHttpHeaderRestrictionFilter.java:84)
19:02:53  	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
19:02:53  	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
19:02:53  	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
19:02:53  	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:160)
19:02:53  	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
19:02:53  	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
19:02:53  	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:160)
19:02:53  	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
19:02:53  	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
19:02:53  	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:94)
19:02:53  	at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
19:02:53  	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
19:02:53  	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:54)
19:02:53  	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
19:02:53  	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
19:02:53  	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
19:02:53  	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
19:02:53  	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
19:02:53  	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
19:02:53  	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:106)
19:02:53  	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:97)
19:02:53  	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
19:02:53  	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223)
19:02:53  	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
19:02:53  	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
19:02:53  	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97)
19:02:53  	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
19:02:53  	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)
19:02:53  	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
19:02:53  	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:63)
19:02:53  	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
19:02:53  	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:111)
19:02:53  	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:172)
19:02:53  	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
19:02:53  	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
19:02:53  	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:53)
19:02:53  	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
19:02:53  	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
19:02:53  	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86)
19:02:53  	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
19:02:53  	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
19:02:53  	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
19:02:53  	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
19:02:53  	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
19:02:53  	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38)
19:02:53  	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
19:02:53  	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
19:02:53  	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
19:02:53  	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
19:02:53  	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:549)
19:02:53  	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
19:02:53  	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
19:02:53  	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571)
19:02:53  	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
19:02:53  	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1378)
19:02:53  	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
19:02:53  	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
19:02:53  	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544)
19:02:53  	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
19:02:53  	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1300)
19:02:53  	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
19:02:53  	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
19:02:53  	at org.eclipse.jetty.server.Server.handle(Server.java:562)
19:02:53  	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
19:02:53  	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
19:02:53  	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
19:02:53  	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
19:02:53  	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
19:02:53  	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
19:02:53  	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
19:02:53  	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
19:02:53  	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
19:02:53  	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
19:02:53  	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
19:02:53  	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)
19:02:53  	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
19:02:53  	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
19:02:53  Caused: java.io.IOException: Failed to load build state
19:02:53  	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$3.onSuccess(CpsFlowExecution.java:848)
19:02:53  	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$3.onSuccess(CpsFlowExecution.java:844)
19:02:53  	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$5$1.run(CpsFlowExecution.java:920)
19:02:53  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38)
19:02:53  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
19:02:53  	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
19:02:53  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
19:02:53  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:30)
19:02:53  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:70)
19:02:53  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
19:02:53  	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
19:02:53  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
19:02:53  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
19:02:53  	at java.base/java.lang.Thread.run(Unknown Source)
19:02:55  [GitHub Checks] GitHub check (name: Jenkins, status: completed) has been published.
19:02:56  Finished: FAILURE
```

Attaching the templates in a tar; this is the pipeline config used on the multibranch project:

```groovy
jte {
  pipeline_template = 'ci_build_and_publish'
}

libraries {
  git

  python {
    version = '3'
    build_tool = 'tox'
  }

  docker {
    registry      = '972669253934.dkr.ecr.eu-central-1.amazonaws.com'
    repository    = 's3clamd'
    credential_id = 'ecr:eu-central-1:aws:registry'
    cleanup       = true
  }
}
```

[jenkins-templates.tgz](https://github.com/jenkinsci/templating-engine-plugin/files/9632757/jenkins-templates.tgz)

**Comment by AFriemann** [comment]
Do you prefer if I open a new issue @steven-terrana @cokieffebah ?
