### ISSUE TITLE
JTE 2.2.2 - random serialization issues in pipeline at various stages

### ISSUE THREAD

**Issue by tusharsisode** [jenkinsci/templating-engine-plugin#207]
### Environment Information

- [x] Jenkins version 2.277.3
- [x] Plugin version 2.2.2
- [x] OS RHEL 7
- [x] Installed plugins:
 ace-editor:1.1
amazon-ecr:1.6
analysis-model-api:9.8.1
ansible:1.1
ansicolor:0.7.5
ant:1.11
antisamy-markup-formatter:2.1
apache-httpcomponents-client-4-api:4.5.13-1.0
artifactory:3.10.6
authentication-tokens:1.4
aws-credentials:1.28.1
aws-java-sdk:1.11.976
basic-branch-build-strategies:1.3.2
blueocean:1.24.3
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.24.3
blueocean-commons:1.24.3
blueocean-config:1.24.3
blueocean-core-js:1.24.3
blueocean-dashboard:1.24.3
blueocean-display-url:2.3.1
blueocean-events:1.24.3
blueocean-git-pipeline:1.24.3
blueocean-github-pipeline:1.24.3
blueocean-i18n:1.24.3
blueocean-jira:1.24.3
blueocean-jwt:1.24.3
blueocean-personalization:1.24.3
blueocean-pipeline-api-impl:1.24.3
blueocean-pipeline-editor:1.24.3
blueocean-pipeline-scm-api:1.24.3
blueocean-rest:1.24.3
blueocean-rest-impl:1.24.3
blueocean-web:1.24.3
bootstrap4-api:4.6.0-2
bouncycastle-api:2.20
branch-api:2.6.3
build-failure-analyzer:2.0.0
build-monitor-plugin:1.12+build.201809061734
build-timeout:1.20
build-token-root:1.7
build-user-vars-plugin:1.7
cctray-xml:1.0
checks-api:1.6.1
cloudbees-bitbucket-branch-source:2.9.7
cloudbees-folder:6.15
cobertura:1.16
code-coverage-api:1.3.2
command-launcher:1.5
conditional-buildstep:1.4.1
config-file-provider:3.7.1
configuration-as-code:1.47
copyartifact:1.46
credentials:2.3.15
credentials-binding:1.24
dashboard-view:2.15
data-tables-api:1.10.23-3
date-parameter:0.0.4
dependency-check-jenkins-plugin:5.1.1
disable-github-multibranch-status:1.2
display-url-api:2.3.4
docker-commons:1.17
docker-workflow:1.23
dtkit-api:3.0.0
durable-task:1.35
ec2:1.55
echarts-api:5.0.1-1
email-ext:2.82
external-monitor-job:1.7
external-workspace-manager:1.2.2
favorite:2.3.3
font-awesome-api:5.15.2-2
forensics-api:1.0.0
gatling:1.3.0
git:4.7.0
git-client:3.7.0
git-server:1.9
github:1.33.1
github-api:1.123
github-branch-source:2.10.2
global-build-stats:1.5
google-oauth-plugin:1.0.4
gradle:1.36
greenballs:1.15.1
groovy:2.3
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
htmlpublisher:1.25
http_request:1.8.27
icon-shim:3.0.0
ivy:2.1
jackson2-api:2.12.1
jacoco:3.1.1
javadoc:1.6
jaxb:2.3.0.1
jdk-tool:1.5
jenkins-design-language:1.24.5
jira:3.2.1
jjwt-api:0.11.2-9.c8b45b8bb173
job-dsl:1.77
job-restrictions:0.8
jobConfigHistory:2.26
jquery-detached:1.2.1
jquery3-api:3.5.1-3
jsch:0.1.55.2
junit:1.49
kubernetes-client-api:4.11.1
kubernetes-credentials:0.8.0
kubernetes:1.27.7
ldap:2.4
log-parser:2.1
mailer:1.34
mapdb-api:1.0.9.0
matrix-auth:2.6.6
matrix-project:1.18
maven-plugin:3.10
mercurial:2.14
metrics:4.0.2.7
momentjs:1.1.1
monitoring:1.86.0
multiple-scms:0.6
nested-view:1.17
node-iterator-api:1.5.0
Office-365-Connector:4.14.0
oauth-credentials:0.4
okhttp-api:3.14.9
pam-auth:1.6
parameterized-trigger:2.40
performance:3.19
pipeline-aws:1.43
pipeline-build-step:2.13
pipeline-github-lib:1.0
pipeline-graph-analysis:1.10
pipeline-input-step:2.12
pipeline-milestone-step:1.3.2
pipeline-model-api:1.8.0
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.6.0
pipeline-model-extensions:1.7.2
pipeline-rest-api:2.19
pipeline-stage-step:2.5
pipeline-stage-tags-metadata:1.8.4
pipeline-stage-view:2.19
pipeline-utility-steps:2.7.0
plain-credentials:1.7
plugin-util-api:2.1.0
popper-api:1.16.1-2
postbuildscript:2.11.0
pubsub-light:1.13
qtest:1.4.6
rebuild:1.32
resource-disposer:0.15
robot:3.0.0
run-condition:1.5
saml:2.0.2
scm-api:2.6.4
script-security:1.76
simple-theme-plugin:0.6
snakeyaml-api:1.27.0
splunk-devops:1.9.6
splunk-devops-extend:1.9.6
sse-gateway:1.24
ssh-credentials:1.18.1
ssh-slaves:1.31.5
structs:1.22
templating-engine:2.2.2
timestamper:1.12
token-macro:2.15
trilead-api:1.0.13
uno-choice:2.5.6
validating-string-parameter:2.8
variant:1.4
warnings-ng:8.10.1
windows-slaves:1.7
workflow-aggregator:2.6
lockable-resources:2.10
workflow-api:2.42
workflow-basic-steps:2.23
workflow-cps:2.85
workflow-cps-global-lib:2.16
workflow-durable-task-step:2.38
workflow-job:2.40
workflow-multibranch:2.22
workflow-scm-step:2.12
workflow-step-api:2.23
workflow-support:3.8
ws-cleanup:0.39
xunit:3.0.1
mask-passwords:3.0

### Description

Trying to upgrade from JTE 1.7.1 to the most latest version 2.2.2.  All the necessary changes to the pipeline are done as per 2.x upgrade instructions. The pipeline has been failing at several stages due to serialization errors after the upgrade. Please note that all of the pipeline code has been working with no issues on version 1.x  Can you please help investigate and fix this issue? Thanks

```bash
hudson.remoting.ProxyException: java.lang.UnsupportedOperationException: Refusing to marshal org.codehaus.groovy.runtime.GStringImpl for security reasons; see https://jenkins.io/redirect/class-filter/
	at hudson.util.XStream2$BlacklistedTypesConverter.marshal(XStream2.java:540)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
	at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:79)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
	at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:79)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87)
	at com.thoughtworks.xstream.converters.reflection.SerializableConverter$1.writeToStream(SerializableConverter.java:139)
	at com.thoughtworks.xstream.core.util.CustomObjectOutputStream.writeObjectOverride(CustomObjectOutputStream.java:87)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
	at java.util.LinkedHashMap.internalWriteEntries(LinkedHashMap.java:333)
	at java.util.HashMap.writeObject(HashMap.java:1363)
	at sun.reflect.GeneratedMethodAccessor408.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.thoughtworks.xstream.core.util.SerializationMembers.callWriteObject(SerializationMembers.java:154)
Caused: hudson.remoting.ProxyException: com.thoughtworks.xstream.converters.ConversionException: Failed calling method
---- Debugging information ----
message             : Failed calling method
cause-exception     : java.lang.UnsupportedOperationException
cause-message       : Refusing to marshal org.codehaus.groovy.runtime.GStringImpl for security reasons; see https://jenkins.io/redirect/class-filter/
method              : org.boozallen.plugins.jte.init.governance.config.dsl.PipelineConfigurationDsl$ConfigBlockMap.writeObject()
-------------------------------
	at com.thoughtworks.xstream.core.util.SerializationMembers.callWriteObject(SerializationMembers.java:158)
	at com.thoughtworks.xstream.converters.reflection.SerializableConverter.doMarshal(SerializableConverter.java:257)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:275)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:262)
Caused: hudson.remoting.ProxyException: java.lang.RuntimeException: Failed to serialize org.boozallen.plugins.jte.init.primitives.injectors.StepWrapper#config for class org.boozallen.plugins.jte.init.primitives.injectors.StepWrapper
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:266)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:233)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:150)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:219)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:158)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:275)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:262)
Caused: hudson.remoting.ProxyException: java.lang.RuntimeException: Failed to serialize org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveNamespace#primitives for class org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveNamespace
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:266)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:233)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:150)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:219)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:158)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:275)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:262)
Caused: hudson.remoting.ProxyException: java.lang.RuntimeException: Failed to serialize org.boozallen.plugins.jte.init.primitives.injectors.LibraryNamespace#libraries for class org.boozallen.plugins.jte.init.primitives.injectors.LibraryNamespace
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:266)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:233)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:150)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:219)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:158)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:275)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:262)
Caused: hudson.remoting.ProxyException: java.lang.RuntimeException: Failed to serialize org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveCollector#namespaces for class org.boozallen.plugins.jte.init.primitives.TemplatePrimitiveCollector
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:266)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:233)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:150)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:219)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:158)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:275)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:262)
Caused: hudson.remoting.ProxyException: java.lang.RuntimeException: Failed to serialize hudson.model.Actionable#actions for class org.jenkinsci.plugins.workflow.job.WorkflowRun
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:266)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:233)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:150)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:219)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:158)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1255)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1244)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1217)
	at hudson.XmlFile.write(XmlFile.java:195)
Caused: hudson.remoting.ProxyException: java.io.IOException: java.lang.RuntimeException: Failed to serialize hudson.model.Actionable#actions for class org.jenkinsci.plugins.workflow.job.WorkflowRun
	at hudson.XmlFile.write(XmlFile.java:202)
	at org.jenkinsci.plugins.workflow.support.PipelineIOUtils.writeByXStream(PipelineIOUtils.java:30)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.save(WorkflowRun.java:1210)
	at hudson.tasks.junit.JUnitResultArchiver.parseAndSummarize(JUnitResultArchiver.java:285)
	at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:63)
	at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:29)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
Caused: hudson.remoting.ProxyException: org.codehaus.groovy.runtime.InvokerInvocationException: java.io.IOException: java.lang.RuntimeException: Failed to serialize hudson.model.Actionable#actions for class org.jenkinsci.plugins.workflow.job.WorkflowRun
	at org.boozallen.plugins.jte.init.primitives.injectors.StepWrapperCPS.invoke(script16202602129371562650911.groovy:69)
	at org.boozallen.plugins.jte.init.primitives.injectors.StepWrapperCPS.call(script16202602129371562650911.groovy:41)
	at org.boozallen.plugins.jte.init.primitives.injectors.StageCPS.call(script16202601827791433282508.groovy:50)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2056)
	at org.boozallen.plugins.jte.init.primitives.injectors.StageCPS.call(script16202601827791433282508.groovy:43)
	at WorkflowScript.run(WorkflowScript:39)
Caused: hudson.remoting.ProxyException: org.codehaus.groovy.runtime.InvokerInvocationException: org.codehaus.groovy.runtime.InvokerInvocationException: java.io.IOException: java.lang.RuntimeException: Failed to serialize hudson.model.Actionable#actions for class org.jenkinsci.plugins.workflow.job.WorkflowRun
	at org.boozallen.plugins.jte.init.primitives.injectors.StepWrapperCPS.invoke(script16202601825141562650911.groovy:69)
	at org.boozallen.plugins.jte.init.primitives.injectors.StepWrapperCPS.call(script16202601825141562650911.groovy:41)
	at WorkflowScript.run(WorkflowScript:35)
	at ___cps.transform___(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.constructorCall(DefaultInvoker.java:25)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:97)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor610.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)
	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

**Comment by steven-terrana** [comment]
Hey @tusharsisode, 

A few questions: 

1. Can you provide a minimal case that reproduces the problem?
2. When during pipeline execution does this happen? while the configuration files are being loaded, when trying to execute a step, etc?

**Comment by tusharsisode** [comment]
Hey @steven-terrana,

1. What I have observed is that this error occurs when a particular step is repeated in the same stage. For example, in our scripted pipeline we call `junit` step multiple times as part of unit testing stage. The pipeline fails with the said serialization errors during the 2nd call to `junit`. Similar behaviour is also observed when we try to execute `rm -rf` via `sh`. The pipeline fails on  subsequent calls to `rm -rf` .
2. All the libraries and configuration files are loaded successfully. This error just occurs midway while pipeline is executing the stages as explained in # 1 .

**Comment by chrishiner** [comment]
I added -Dhudson.remoting.ClassFilter=org.codehaus.groovy.runtime.GStringImpl to my startup options to work around this. I assumed that somewhere in our scripts were were doing something in a string that made it into a GString instead of a regular String.

**Comment by tusharsisode** [comment]
Yeah, I already tried adding `-Dhudson.remoting.ClassFilter=org.codehaus.groovy.runtime.GStringImpl` to the startup java options before posting this issue. However, it didn't quite help resolve the issue. Even if it would have, I am not quite comfortable adding this from security standpoint. Don't know if this class has any dangerous deserialisation semantics.

**Comment by tusharsisode** [comment]
Hey @steven-terrana ,

Do we have any feedback/updates on this issue yet?

**Comment by cokieffebah** [comment]
sorry just looked at this.  @tusharsisode, 
> Can you provide a minimal case that reproduces the problem?

could you give us some minimal code to reproduce, Jenkinsfile, pipeline_config.groovy.  Thanks

**Comment by tusharsisode** [comment]
Hi @cokieffebah ,

Sorry that it took so long to respond. I was able to reproduce this issue with some minimal code. You can see the pipeline code here - https://github.com/tusharsisode/pipeline

Detailed log from running this pipeline is attached below.
[jte2.2_run_log.txt](https://github.com/jenkinsci/templating-engine-plugin/files/6621568/jte2.2_run_log.txt)

This issue occurs when an interpolated string value is set inside a library config as depicted here -  https://github.com/tusharsisode/pipeline/blob/main/libraries/gradle/steps/code_build.groovy#L11

I request that this issue be prioritized and fixed soon.

Cheers.

**Comment by mxkmp** [comment]
Having the same issue while migrating from 1.7 to 2.2. I described my issue in: https://gitter.im/jenkinsci/templating-engine-plugin?at=60d0b5c8457e19611a0f1f96.

**Comment by cokieffebah** [comment]
@mxkmp thanks for the submission

**Comment by mxkmp** [comment]
I think there is a problem with the writeObject of the GString Objects in general. In the build step two different image names are defined.
```
    imageName = "${pipelineConfig.globals.artifactorySubFolder}/${pipelineConfig.globals.artifactoryDockerPrefix}-${pipelineConfig.globals.serviceName}" 
    pipelineConfig.globals.localBuildImage = "${imageName}-build:${commit}"
    pipelineConfig.globals.localImageName = "${imageName}:${commit}"
```
If I change the localBuildImage and localImageName to a String there are no errors in the next step (lint). Before running the docker inside step jenkins maybe tries to persists its pipelineConfig variables and is not allowed to persist the GString. How can I avoid this behavior?

**Comment by cokieffebah** [comment]
@mxkmp try `pipelineConfig.globals.localBuildImage = "${imageName}-build:${commit}".toString()` basically `toString()` your GString

**Comment by mxkmp** [comment]
Yes I tried it before and it works. Is there a better way or will the security plugin block every GString in the memory?

**Comment by fdolsky321** [comment]
I have the same issue in this code:

```
package libraries.git.steps

String getCommitAuthor() {
    try {
        return sh(returnStdout: true, script: "git show -s --format='%ae'".toString()).trim()
    } catch(ignored) {
        return ""
    }
}
```
Even casting to String didnt help me in this case. Any idea, guys?
