### ISSUE TITLE
[Bug]: Global variable keyword usecase example fails with Sandbox errors.

### ISSUE THREAD

**Issue by Tingles** [jenkinsci/templating-engine-plugin#246]
### Jenkins Version

Jenkins 2.303.3

### JTE Version

2.3

### Bug Description

The documented example detailing the global config variable use case of the Keyword primitive [(here)](https://jenkinsci.github.io/templating-engine-plugin/2.3/concepts/pipeline-primitives/keywords/#global-variables) errors.

### Relevant log output

```shell
Seen 3 remote branches
[JTE] Obtained Template Configuration File (show)
java.lang.SecurityException: Rejecting unsandboxed property set: Script1.one = java.lang.Integer
	at org.kohsuke.groovy.sandbox.impl.RejectEverythingInterceptor.onSetProperty(RejectEverythingInterceptor.java:74)
	at org.kohsuke.groovy.sandbox.impl.Checker$8.call(Checker.java:409)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedSetProperty(Checker.java:416)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedSetProperty(Checker.java:385)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedSetProperty(Checker.java:385)
	at org.kohsuke.groovy.sandbox.impl.Checker$checkedSetProperty$2.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
	at Script1$_run_closure3$_closure6.doCall(Script1.groovy:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at groovy.lang.GString.writeTo(GString.java:177)
	at groovy.lang.GString.toString(GString.java:155)
	at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:630)
	at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:577)
	at org.codehaus.groovy.runtime.InvokerHelper.toString(InvokerHelper.java:132)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.join(DefaultGroovyMethods.java:6022)
	at org.codehaus.groovy.runtime.dgm$379.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.boozallen.plugins.jte.init.governance.config.dsl.PipelineConfigurationDsl.serialize(PipelineConfigurationDsl.groovy:101)
	at org.boozallen.plugins.jte.init.governance.config.dsl.PipelineConfigurationDsl$serialize$0.call(Unknown Source)
	at org.boozallen.plugins.jte.init.governance.config.dsl.PipelineConfigurationObject.plus(PipelineConfigurationObject.groovy:59)
	at org.boozallen.plugins.jte.init.governance.config.dsl.PipelineConfigurationObject$plus.call(Unknown Source)
	at org.boozallen.plugins.jte.init.PipelineDecorator.aggregatePipelineConfigurations(PipelineDecorator.groovy:84)
	at org.boozallen.plugins.jte.init.PipelineDecorator.initialize(PipelineDecorator.groovy:61)
	at org.boozallen.plugins.jte.init.PipelineDecorator$initialize.call(Unknown Source)
	at org.boozallen.plugins.jte.job.TemplateFlowDefinition.initializeJTE(TemplateFlowDefinition.groovy:67)
	at jdk.internal.reflect.GeneratedMethodAccessor916.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at org.boozallen.plugins.jte.job.TemplateFlowDefinition.create(TemplateFlowDefinition.groovy:60)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:310)
	at hudson.model.ResourceController.execute(ResourceController.java:99)
	at hudson.model.Executor.run(Executor.java:431)
Finished: FAILURE
```

### Steps to Reproduce

Minimal jenkins docker container.
Multibranch pipline job.

Use this as my pipeline_config.groovy:
```groovy
  1 libraries {
  2     git
  3 }
  4 
  5 stages {
  6     continuous_integration {
  7         configure
  8         build
  9         unittest
 10     }
 11 }
 12 
 13 keywords {
 14     globals = {
 15         one = 1
 16         two = 2
 17     }
 18 }
 19 
 20 template_methods {
 21     configure
 22     build
 23     unittest
 24     deploy
 25     smoke_test
 26 }
```

**Comment by Tingles** [comment]
Closed, just realized I had an assignment expression, so the example was not verbatim from the documentation.
