### ISSUE TITLE
NotSerializableException: java.lang.reflect.Method

### ISSUE THREAD

**Issue by iamascript** [jenkinsci/templating-engine-plugin#26]
I have been getting intermittent (but frequent) build failures since upgrading to JTE version 1.3 from 1.1.1.

Please find the stack trace below.

So far this appears to happen only inside a parallel() block of my scripted pipeline.

Attaching a debugger, `com.cloudbees.groovy.cps.impl.FunctionCallEnv.locals` refers to `org.boozallen.plugins.jte.hooks.Hooks`, specifically the section that iterates through methods:

```
stepWrappers.each{ step ->
   step.impl.class.methods.each{ method ->
      if (method.getAnnotation(a)){
         AnnotatedMethod am = new AnnotatedMethod(a.getSimpleName(), method.name, step)
         discovered.push(am) 
      }            
   }
}
```

Adding @NonCPS to `discover(Class<? extends Annotation> a, TemplateBinding b)` appears to fix the issue, but I don't know if that would be a correct solution.

The stack trace is:

```java.io.NotSerializableException: java.lang.reflect.Method
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:926)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:844)
(parts skipped here)
at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1040)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:1019)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
(parts skipped here)
        at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:920)
        at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
        at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:111)
        at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.lambda$writeObject$0(RiverWriter.java:144)
        at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:241)
        at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.writeObject(RiverWriter.java:143)
        at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:523)
        at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:499)
        at org.jenkinsci.plugins.workflow.cps.CpsStepContext$3.onSuccess(CpsStepContext.java:531)
(parts skipped here)
```

```Caused by: an exception which occurred:
        in field com.cloudbees.groovy.cps.impl.FunctionCallEnv.locals
        in object com.cloudbees.groovy.cps.impl.FunctionCallEnv@1f3c4ffd
        in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
        in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@3af6683
        in field com.cloudbees.groovy.cps.impl.CallEnv.caller
        in object com.cloudbees.groovy.cps.impl.FunctionCallEnv@2c34353f
        in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
        in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@5c4e9fdf
        in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
        in object com.cloudbees.groovy.cps.impl.LoopBlockScopeEnv@6f00f6be
        in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
        in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@353af2c6
        in field com.cloudbees.groovy.cps.impl.CallEnv.caller
        in object com.cloudbees.groovy.cps.impl.ClosureCallEnv@638465d3
        in field com.cloudbees.groovy.cps.impl.ProxyEnv.parent
        in object com.cloudbees.groovy.cps.impl.BlockScopeEnv@2249d814
        in field com.cloudbees.groovy.cps.impl.CallEnv.caller
        in object com.cloudbees.groovy.cps.impl.FunctionCallEnv@4ee1edbb
        in field com.cloudbees.groovy.cps.Continuable.e
        in object org.jenkinsci.plugins.workflow.cps.SandboxContinuable@4a1d37ad
        in field org.jenkinsci.plugins.workflow.cps.CpsThread.program
        in object org.jenkinsci.plugins.workflow.cps.CpsThread@546b40f7
        in field org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.threads
        in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@746deff9
        in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@746deff9
```

**Comment by steven-terrana** [comment]
Thank you for letting us know! JTE 1.4 was just released incorporating @linead's fix!

**Comment by steven-terrana** [comment]
after upgrading, will you please confirm whether you continue to see this issue?
