### ISSUE TITLE
[Bug]: Update to Jenkins Templating Engine 2.4 cause null pointer exception

### ISSUE THREAD

**Issue by e88z4** [jenkinsci/templating-engine-plugin#264]
### Jenkins Version

2.319.3

### JTE Version

2.4

### Bug Description

This bug is related to JTE version 2.4.
Last night, we upgraded JTE plugin from 2.3 to 2.4. After the plugin update, all the Bitbucket multibranch + JTE setup starting to fail right away. 

Downgrading the JTE plugin from 2.4 to 2.3 will make the job running again without any issue.

Some relevant detail about the other plugin that may be useful
Bitbucket Branch Source plugin version 757.vddedc5f2589a

### Relevant log output

```shell
[JTE] Obtained Pipeline Configuration File 
[JTE] -- scm: git ssh://git@mycorp.com/csma/jte-pipeline-configuration.git
[JTE] -- file path: pipeline-configuration/pipeline_config.groovy
[JTE] Pipeline Configuration Modifications 
[JTE] Configurations Added:
[JTE] - libraries.git set to [:]
[JTE] - libraries.jenkins set to [:]
[JTE] - libraries.utility set to [:]
[JTE] - libraries.pod_template.cloud set to my-cloud-namespace-ns
[JTE] - libraries.pod_template.build_agent.sdk.image set to maven:3.8.4-openjdk-11
[JTE] - libraries.pod_template.build_agent.sdk.resource.cpu.request_mcore set to 1000
[JTE] - libraries.pod_template.build_agent.sdk.resource.cpu.limit_mcore set to 2000
[JTE] - libraries.pod_template.build_agent.sdk.resource.memory.request_mbyte set to 2000
[JTE] - libraries.pod_template.build_agent.sdk.resource.memory.limit_mbyte set to 4000
[JTE] - libraries.pod_template.build_agent.docker_build.enabled set to false
[JTE] - keywords.development set to ^([Dd]evelop(ment|er|))|([Hh]otfix/.*)|([Ff]eature/.*)|([Pp][Rr]-.*)|([Rr]elease/.)|([Mm](aster|ain))$
[JTE] - keywords.release_candidate set to ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-rc\.(0|[1-9]\d*))$
[JTE] - keywords.release set to ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$
[JTE] Configurations Deleted: None
[JTE] Configurations Changed: None
[JTE] Configurations Duplicated: None
[JTE] Configurations Ignored: None
[JTE] Subsequent May Merge:
[JTE] - libraries
[JTE] Subsequent May Override:
[JTE] - libraries.pod_template.cloud
[JTE] - libraries.pod_template.build_agent.sdk.image
[JTE] - libraries.pod_template.build_agent.sdk.resource
[JTE] - libraries.pod_template.build_agent.docker_build.enabled
java.lang.NullPointerException
	at jenkins.scm.api.SCMFile.child(SCMFile.java:151)
	at jenkins.scm.api.SCMFileSystem.child(SCMFileSystem.java:130)
	at jenkins.scm.api.SCMFileSystem$child$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at jenkins.scm.api.SCMFileSystem$child$0.call(Unknown Source)
	at org.boozallen.plugins.jte.util.FileSystemWrapper.getFileContents(FileSystemWrapper.groovy:70)
	at org.boozallen.plugins.jte.util.FileSystemWrapper$getFileContents$4.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at org.boozallen.plugins.jte.init.PipelineConfigurationAggregator.getJobPipelineConfiguration(PipelineConfigurationAggregator.groovy:85)
	at org.boozallen.plugins.jte.init.PipelineConfigurationAggregator.aggregate(PipelineConfigurationAggregator.groovy:62)
	at org.boozallen.plugins.jte.init.PipelineConfigurationAggregator$aggregate.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at org.boozallen.plugins.jte.job.TemplateFlowDefinition.initializePipeline(TemplateFlowDefinition.groovy:76)
	at org.boozallen.plugins.jte.job.TemplateFlowDefinition$initializePipeline.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at org.boozallen.plugins.jte.job.TemplateFlowDefinition.create(TemplateFlowDefinition.groovy:63)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:310)
	at hudson.model.ResourceController.execute(ResourceController.java:99)
	at hudson.model.Executor.run(Executor.java:432)
Finished: FAILURE
```

### Steps to Reproduce

1. Upgrade JTE plugin from 2.3 to 2.4
2. Run the pipeline

**Comment by steven-terrana** [comment]
Thanks for reporting - which job type were you seeing this happen on? 
MultiBranch project?

**Comment by e88z4** [comment]
Hi @steven-terrana ,
Yes, it is a Bitbucket multibranch project.

**Comment by cokieffebah** [comment]
guessing its this code that was added: 
https://github.com/jenkinsci/templating-engine-plugin/blob/main/src/main/groovy/org/boozallen/plugins/jte/init/PipelineConfigurationAggregator.groovy#L79-L84

            String configurationPath
            if (flowDefinition instanceof MultibranchTemplateFlowDefinition) {
                configurationPath = flowDefinition.getConfigurationPath()
            } else {
                configurationPath = ScmPipelineConfigurationProvider.CONFIG_FILE
            }

previous the value was just: ScmPipelineConfigurationProvider.CONFIG_FILE, we probably need to decide if it defaults to this or if it should error/fail if the flowDefinition.getConfigurationPath() is empty

**Comment by gdisanto** [comment]
Facing same the same issue here. I am providing a pipeline configuration at Multibranch project level cause I do not want the "pipeline_config.groovy" file in the repositories.

**Comment by anthony-zawacki** [comment]
Hopefully this might save people a bit of hunting on how to fix this error.  As mentioned by @cokieffebah the behavior has changed on multibranch projects.  Where before the config file always defaulted to pipeline_config.groovy, now it needs to be specified.  We use DSL to configure our projects, and the correct values are the default values.

However, when the build is failing, if I click on the job that was failing, then clicked configure and then click save without changing anything, the build works.  Comparing the job_config.xml files between a job that worked and a job that didn't work let to the discovery that JTE 2.4 added three configuration parameters to the project.

In our DSL, we added this:
```
multibranchPipelineJob("project_name") {
# old configuration unchanged
# just added this at the bottom of each job:
    factory {
        templateBranchProjectFactory {
            configurationPath('pipeline_config.groovy')
            scriptPath('Jenkinsfile')
            filterBranches(true)
        }
    }
}
```
Our project configurations are now working again with JTE 2.4.

**Comment by gdisanto** [comment]
Hi @anthony-zawacki,
Thanks for that, I am using DSL to configure my projects and I was able to upgrade JTE to 2.4 and fix my builds with your help!.
