### ISSUE TITLE
[Bug]: Slashy string support for string variable name in configuration file

### ISSUE THREAD

**Issue by e88z4** [jenkinsci/templating-engine-plugin#287]
### Jenkins Version

2.319.3

### JTE Version

2.3

### Bug Description

I have a slashy string variable in my configuration file. Does JTE support slashy string for a string variable type?

### Relevant log output

```shell
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 43: unexpected char: '\' @ line 43, column 26.
           product_name = ''\"Augmented Account Factory\"''
                            ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:150)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:120)
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:132)
	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:350)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:139)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:110)
	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:234)
	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:168)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:943)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:736)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:727)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runScript(GroovySandbox.java:162)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript.evaluate(SecureGroovyScript.java:370)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript$evaluate$0.call(Unknown Source)
	at org.boozallen.plugins.jte.init.governance.config.dsl.PipelineConfigurationDsl.parse(PipelineConfigurationDsl.groovy:92)
	at org.boozallen.plugins.jte.init.governance.config.dsl.PipelineConfigurationDsl$parse.call(Unknown Source)
	at org.boozallen.plugins.jte.init.governance.config.dsl.PipelineConfigurationObject.plus(PipelineConfigurationObject.groovy:59)
	at org.boozallen.plugins.jte.init.governance.config.dsl.PipelineConfigurationObject$plus.call(Unknown Source)
	at org.boozallen.plugins.jte.init.PipelineDecorator.aggregatePipelineConfigurations(PipelineDecorator.groovy:84)
	at org.boozallen.plugins.jte.init.PipelineDecorator.initialize(PipelineDecorator.groovy:61)
	at org.boozallen.plugins.jte.init.PipelineDecorator$initialize.call(Unknown Source)
	at org.boozallen.plugins.jte.job.TemplateFlowDefinition.initializeJTE(TemplateFlowDefinition.groovy:67)
	at jdk.internal.reflect.GeneratedMethodAccessor3769.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at org.boozallen.plugins.jte.job.TemplateFlowDefinition.create(TemplateFlowDefinition.groovy:60)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:310)
	at hudson.model.ResourceController.execute(ResourceController.java:99)
```

### Steps to Reproduce

Create pipeline_config.groovy with the following content:

```groovy
application_environments{
    dev{
        product_name = /'"Augmented Account Factory"'/
    }

    prod{
        product_name = /'"Augmented Account Factory"'/
    }
}
```

**Comment by steven-terrana** [comment]
when i take that code:
```groovy
 product_name = ''\"Augmented Account Factory\"''`
```

and just run it in the [Groovy Web Console](https://groovyconsole.appspot.com/) it doesn't compile.

The pipeline config you posted works for me.

you can do:
```groovy
product_name = "\"Augmented Account Factory\""
```

or 
```groovy
product_name = '"Augmented Account Factory"'
```

**Comment by e88z4** [comment]
Hi @steven-terrana , 

I even tried your combination to use single quote, double quote but none of them works. It seems you're not able to re-produce it on your side. I will close this report. It could be something else on my side here.

**Comment by steven-terrana** [comment]
no worries - if you're able to provide a pipeline configuration in a public repo that demonstrates the issue, feel free to reopen.

**Comment by cokieffebah** [comment]
not sure if this matters but do the later versions 2.4, 2.5 demonstrate this issue? or just 2.3
