### ISSUE TITLE
Pipeline always fails when Jenkins master is restarted

### ISSUE THREAD

**Issue by Quaiks** [jenkinsci/templating-engine-plugin#44]
Hello!!

We are testing how resilient are our pipelines and we have discovered that every build using this plugin fails when restarting the master.

```java
java.lang.ClassNotFoundException: script1580725490369752501149
 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
 	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:677)
 	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:787)
 	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:775)
 	at java.base/java.lang.Class.forName0(Native Method)
 	at java.base/java.lang.Class.forName(Class.java:398)
 	at org.jboss.marshalling.AbstractClassResolver.loadClass(AbstractClassResolver.java:123)
 	at org.jboss.marshalling.AbstractClassResolver.resolveClass(AbstractClassResolver.java:104)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadClassDescriptor(RiverUnmarshaller.java:1022)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1355)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:272)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:220)
 	at org.jboss.marshalling.river.RiverUnmarshaller.readFields(RiverUnmarshaller.java:1853)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1767)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1715)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1395)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:272)
 	at org.jboss.marshalling.river.BlockUnmarshaller.readObject(BlockUnmarshaller.java:149)
 	at org.jboss.marshalling.river.BlockUnmarshaller.readObject(BlockUnmarshaller.java:135)
 	at org.jboss.marshalling.MarshallerObjectInputStream.readObjectOverride(MarshallerObjectInputStream.java:53)
 	at org.jboss.marshalling.river.RiverObjectInputStream.readObjectOverride(RiverObjectInputStream.java:307)
 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:424)
 	at java.base/java.util.HashMap.readObject(HashMap.java:1460)
 	at java.base/jdk.internal.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 	at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.callReadObject(JDKSpecific.java:179)
 	at org.jboss.marshalling.reflect.SerializableClass.callReadObject(SerializableClass.java:212)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1746)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1395)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:272)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:220)
 	at org.jboss.marshalling.river.RiverUnmarshaller.readFields(RiverUnmarshaller.java:1853)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doInitSerializable(RiverUnmarshaller.java:1767)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadNewObject(RiverUnmarshaller.java:1395)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:272)
 	at org.jboss.marshalling.river.RiverUnmarshaller.doReadObject(RiverUnmarshaller.java:205)
 	at org.jboss.marshalling.AbstractObjectInput.readObject(AbstractObjectInput.java:41)
 	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverReader$SandboxedUnmarshaller.lambda$readObject$0(RiverReader.java:250)
 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:237)
 	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverReader$SandboxedUnmarshaller.sandbox(RiverReader.java:237)
 	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverReader$SandboxedUnmarshaller.readObject(RiverReader.java:250)
 	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$2.onSuccess(CpsFlowExecution.java:783)
 	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$2.onSuccess(CpsFlowExecution.java:776)
 	at org.jenkinsci.plugins.workflow.support.concurrent.Futures$1.run(Futures.java:150)
 	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253)
 	at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:149)
 	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:134)
 	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:170)
 	at org.jenkinsci.plugins.workflow.support.concurrent.ChainingListenableFuture.access$000(ChainingListenableFuture.java:33)
 	at org.jenkinsci.plugins.workflow.support.concurrent.ChainingListenableFuture$1.run(ChainingListenableFuture.java:196)
 	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253)
 	at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:149)
 	at com.google.common.util.concurrent.ExecutionList.add(ExecutionList.java:105)
 	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:155)
 	at org.jenkinsci.plugins.workflow.support.concurrent.ChainingListenableFuture.run(ChainingListenableFuture.java:189)
 	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253)
 	at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:149)
 	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:134)
 	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:170)
 	at org.jenkinsci.plugins.workflow.support.concurrent.ChainingListenableFuture.access$000(ChainingListenableFuture.java:33)
 	at org.jenkinsci.plugins.workflow.support.concurrent.ChainingListenableFuture$1.run(ChainingListenableFuture.java:196)
 	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253)
 	at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:149)
 	at com.google.common.util.concurrent.ExecutionList.add(ExecutionList.java:105)
 	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:155)
 	at org.jenkinsci.plugins.workflow.support.concurrent.ChainingListenableFuture.run(ChainingListenableFuture.java:189)
 	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253)
 	at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:149)
 	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:134)
 	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:170)
 	at org.jenkinsci.plugins.workflow.support.concurrent.ListFuture.setOneValue(ListFuture.java:158)
 	at org.jenkinsci.plugins.workflow.support.concurrent.ListFuture.access$000(ListFuture.java:40)
 	at org.jenkinsci.plugins.workflow.support.concurrent.ListFuture$2.run(ListFuture.java:107)
 	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253)
 	at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:149)
 	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:134)
 	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:170)
 	at org.jenkinsci.plugins.workflow.support.concurrent.ChainingListenableFuture.access$000(ChainingListenableFuture.java:33)
 	at org.jenkinsci.plugins.workflow.support.concurrent.ChainingListenableFuture$1.run(ChainingListenableFuture.java:196)
 	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253)
 	at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:149)
 	at com.google.common.util.concurrent.ExecutionList.add(ExecutionList.java:105)
 	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:155)
 	at org.jenkinsci.plugins.workflow.support.concurrent.ChainingListenableFuture.run(ChainingListenableFuture.java:189)
 	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:253)
 	at com.google.common.util.concurrent.ExecutionList$RunnableExecutorPair.execute(ExecutionList.java:149)
 	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:134)
 	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:170)
 	at org.jenkinsci.plugins.workflow.support.pickles.TryRepeatedly.access$500(TryRepeatedly.java:48)
 	at org.jenkinsci.plugins.workflow.support.pickles.TryRepeatedly$1.run(TryRepeatedly.java:112)
 	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
 Caused: java.io.IOException: Failed to load build state
 	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$3.onSuccess(CpsFlowExecution.java:855)
 	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$3.onSuccess(CpsFlowExecution.java:853)
 	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$4$1.run(CpsFlowExecution.java:907)
 	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38)
 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at java.base/java.lang.Thread.run(Thread.java:834)
```

Any ideas about how we can improve the plugin to avoid this?

Regards!

**Comment by steven-terrana** [comment]
hey @Quaiks -  i knew eventually this would come back to bite us :). 

I don't know the exact fix, but i know this issue is related to how we're loading libraries and transforming them into steps. 

I would probably look heavily at how the existing Jenkins shared libraries (non-JTE) implement their serialization. 

Is there an easy to reproduce test case I can use when debugging?

**Comment by Quaiks** [comment]
Hello!! Our pipelines are quite big. I will try to build a small one but we have a lot of use cases and happens in all of theme.

**Comment by Quaiks** [comment]
We were using [MPL](https://github.com/griddynamics/mpl) before this plugin. We did not have any restart issue with that library. Maybe it helps.

**Comment by Quaiks** [comment]
CPS is pretty like a magic black box to me but... What if instead of creating a `Script` instance, we create a `CpsScript` instance in [here](https://github.com/jenkinsci/templating-engine-plugin/blob/master/src/main/groovy/org/boozallen/plugins/jte/utils/TemplateScriptEngine.groovy#L57)?

I don't know how to help with this one!

**Comment by steven-terrana** [comment]
I'm sorry to hear that @Quaiks - i'm going to try digging into this over the weekend and I will update you when it's resolved.

**Comment by steven-terrana** [comment]
Hey @Quaiks, this has been resolved and the functionality will be a part of the 2.0 release.
