### ISSUE TITLE
Pipeline plugin fails if application project defines new stages with merge or overrides

### ISSUE THREAD

**Issue by yashu23** [jenkinsci/templating-engine-plugin#48]
JTE Plugin version: 1.4

**Scenario**:

**Goverence tier configuration** 
```
stages {
    stage_one {
        override = true
    }
}
```
**Application Configuration**
```
stages {
    stage_two {
        merge = true
    }
    stage_three {
        override = true
    }
}
```

**Expected behaviour**
  Plugin should ignore new stages defined by application configuration

**Actual behaviour:**

Code fails with following error
```
Caused by: java.lang.NullPointerException: Cannot set property 'merge' on null object
	at org.boozallen.plugins.jte.config.TemplateConfigDsl.serialize_closure1$_closure4(TemplateConfigDsl.groovy:84)
	at groovy.lang.Closure.call(Closure.java:418)
	at org.boozallen.plugins.jte.config.TemplateConfigDsl.serialize_closure1(TemplateConfigDsl.groovy:79)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at org.boozallen.plugins.jte.config.TemplateConfigDsl.serialize(TemplateConfigDsl.groovy:67)
	... 1 more
```

It appears plugin assumes any properties added to merge or override set in the application config is also present in parent configuration and it fails while serializing config object

**Comment by steven-terrana** [comment]
thanks for letting us know! i'll take a look
